---
title: Template normalized NM analysis for PPMI
output: html_document
---


```{r setup}
library(magrittr)
library(dplyr)
library(ANTsR)
library(stringr)
library(subtyper)

library(lme4)
library(progress)
library(jtools)
library(ggplot2)
library(gridExtra)

#' Fit Mixed-Effects Models and Analyze Asymmetry with Progress Bar
#'
#' This function fits mixed-effects models for each voxel, computes coefficients, p-values,
#' and optionally generates effect plots if significant. Progress is tracked using a progress bar.
#'
#' @param sncnames Character vector of voxel names to iterate over.
#' @param coefmat Matrix to store t-values of the coefficients.
#' @param coefmatpv Matrix to store p-values of the coefficients.
#' @param coefmatA Matrix to store t-values for asymmetry.
#' @param coefmatpvA Matrix to store p-values for asymmetry.
#' @param ppmiMatchedScl Data frame containing the data for fitting the model.
#' @param dxvar Character string specifying the dependent variable.
#' @param covariates covariate part of equation eg \code{~ (1|commonID)+(1|SITE)+age}
#' @param show_plots Logical, if TRUE, significant effect plots will be printed.
#' @param threshold Numeric, p-value threshold for considering significant results (default is 1e-4).
#'
#' @return coefficient matrices (list of)
#'
#' @examples
#' run_voxel_analysis(sncnames, coefmat, coefmatpv, coefmatA, coefmatpvA, ppmiMatchedScl, "dxvar")
#'
#' @export
run_voxel_analysis <- function(sncnames, coefmat, coefmatpv, coefmatA, coefmatpvA, ppmiMatchedScl, dxvar, covariates, show_plots = TRUE, threshold = 1e-4) {
  
  # Initialize a progress bar
  pb <- progress_bar$new(
    format = "  Processing [:bar] :percent in :elapsed",
    total = length(sncnames), clear = FALSE, width = 60
  )
  effectsX=coefmatpv*0
  effectsA=coefmatpv*0
  
  # Loop over the voxel names
  for (vox in sample(sncnames)) {
    pb$tick()  # Update progress bar
    
    ct <- as.integer(gsub("nmavgsnc.", "", vox, fixed = TRUE))
    voxa <- gsub("nmavgsnc", "nmasmsnc", vox, fixed = TRUE)
    
    if (is.na(coefmat[1, ct])) {
      # Create formulas
      myeq <- as.formula(paste(vox, covariates, dxvar))
      myeqa <- as.formula(paste(voxa, covariates, dxvar))
      
      # Fit mixed models
      mdl <- lmer(myeq, data = ppmiMatchedScl)
      mdla <- lmer(myeqa, data = ppmiMatchedScl)
      
      # Extract coefficients
      mycoef <- coefficients(summary(mdl))
      mycoefA <- coefficients(summary(mdla))
      gg <- grep(dxvar, rownames(mycoef))
      
      # Store coefficients and p-values
      coefmat[, ct] <- mycoef[gg, "t value"]
      coefmatpv[, ct] <- mycoef[gg, "Pr(>|t|)"]
      coefmatA[, ct] <- mycoefA[gg, "t value"]
      coefmatpvA[, ct] <- mycoefA[gg, "Pr(>|t|)"]
      ndf <- round( mycoef[gg, "df"] )
      effectsX[,ct] = effectsize::t_to_d(mycoef[gg, "t value"], ndf )[,1]
      ndf <- round( mycoefA[gg, "df"] )
      effectsA[,ct] = effectsize::t_to_d(mycoefA[gg, "t value"], ndf )[,1]
      
      # Check if any p-value is significant and plot if true
      if (any(mycoef[gg, 5] < threshold) | any(mycoefA[gg, 5] < threshold)) {
        if (show_plots) {
          # Create and customize plots
          mygg <- jtools::effect_plot(mdl, !!sym(dxvar)) +
            ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 0.13)) +
            ggtitle(vox)
          
          myggA <- jtools::effect_plot(mdla, !!sym(dxvar)) +
            ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 0.33)) +
            ggtitle(voxa)
          
          # Print the plots side by side
          print(grid.arrange(grobs = list(mygg, myggA), nrow = 2))
        }
        
        # Print coefficients and equations
        print(mycoef[, -c(1:3)])
        print(mycoefA[, -c(1:3)])
        print(myeq)
        
        # Check significant results
        for (k in 1:nrow(coefmat)) {
          nsig <- sum(p.adjust(na.omit(coefmatpv[k, ]), 'BH') <= 0.05)
          nsig2 <- sum(p.adjust(na.omit(coefmatpvA[k, ]), 'BH') <= 0.05)
          print(paste(rownames(coefmatpvA)[k], nsig, nsig2))
        }
      }
    }
  }

  return( list( 
    coefmat=coefmat,
    coefmatpv=coefmatpv,
    coefmatA=coefmatA,
    coefmatpvA=coefmatpvA,
    effects=effectsX,
    effectsA=effectsA
  ))
}

match_indices <- function(fns, ppmi) {
  # Create a key vector to match
  key <- paste(fns$subjectID, fns$date)
  
  # Create a lookup vector
  lookup <- paste(ppmi$commonID, ppmi$date)
  
  # Find the indices of the matched rows in ppmi
  indices <- match(key, lookup)
  
  # Return the indices
  return(indices)
}

parse_filename <- function(fns) {
  # Split the filename into components
  components <- strsplit(basename(fns$fn), "-")
  
  # Create a data frame with the extracted components
  parsed_fns <- data.frame(
    studyName = sapply(components, function(x) x[1]),
    subjectID = sapply(components, function(x) x[2]),
    date = sapply(components, function(x) x[3]),
    modality = sapply(components, function(x) x[4]),
    remainder = sapply(components, function(x) paste(x[5:length(x)], collapse = "-")),
    stringsAsFactors = FALSE
  )
  
  # Add the original filename and root directory to the data frame
  parsed_fns$fn <- fns$fn
  parsed_fns$root_dir <- dirname(fns$fn)
  
  return(parsed_fns)
}

```

```{r start}
img=antsImageRead("../data/ppmi_NM_multichannel.mha")
nc=img@components
nnz=rep(NA,nc)
zz=splitChannels(img)
for ( k in 1:nc ) {
    temp = cropIndices( zz[[k]], c(1,1,12), c(94,69,17) )
    nnz[k]=sum( temp == 0 )
}
hist( nnz )
table( nnz == 0 )
```


```{r filter}
fns=read.csv("../data/ppmi_NM_filenames.csv")
colnames(fns)=c("count","fn")
names(fns)
nnzthresh = quantile( nnz[nnz>0],0.5)
fns=fns[nnz <= nnzthresh,]
zz=zz[nnz <= nnzthresh ]
head(parse_filename(fns))
# fix fns
fns = fns %>% 
  parse_filename() %>% 
  filter(studyName == "PPMI") %>% 
  select(subjectID, date, modality)

zztest = zz[[1272]]
zzavgImg = antsAverageImages( zz )
# get mask
zzavgmask = antsImageRead("~/.antspymm/PPMI_NM_template_crop_mask.nii.gz")
zzavgmask = antsImageRead("~/Downloads/PPMI_NM_template_crop_mask.nii.gz")
```


```{r match}
if ( ! exists( "ppmi" ) ) {
    ppmi = read.csv( "~/Downloads/ppmi_pym_data/ppmi_idps_trim_v1.4.0_SRF.csv")
}
ppmi2nm = match_indices( fns, ppmi )
zz=zz[!is.na(ppmi2nm)]
ppmi2nm=na.omit(ppmi2nm)
ppmiMatched=ppmi[ppmi2nm,]
# now filter based on standard criteria: NM volume >= 200 & signal <= 2000
volfilt=na2f( ppmiMatched$NM2DMT_NM_volume_substantianigra >= 200 )
sigfilt=na2f(ppmiMatched$NM2DMT_NM_avg_substantianigra <= 2000)
ppmiMatched=ppmiMatched[ volfilt & sigfilt , ]
zz=zz[  volfilt & sigfilt  ]
```

```{r reflection}
if ( ! exists( "doAsym" ) ) doAsym='asymmetry_index'
if (  !exists("zzaind") |  !exists("zzavg") ) {
#    zzavgsmall=resampleImage(zzavgmask,rep(1,3))
#    zzavgrTx = reflectImage( zzavgsmall, axis=0, tx='SyN', verbose=TRUE )
#    antsImageMutualInformation( zzavgrTx$warpedmovout, zzavgsmall )
    binarized = maskImage( mask, mask, level = c( 1, 5 ), binarize=TRUE ) * 2 + 
        maskImage( mask, mask, level = c( 2, 6 ), binarize=TRUE )
    zzavgrTx = reflectImage( binarized, axis=0, tx='antsRegistrationSyNRepro[s]', verbose=TRUE )
    zzaind = list()
    zzavg = list()
    zzmi = list()
    for ( k in 1:length(zz)) {
        temp=antsApplyTransforms( zzavgImg, zz[[k]],zzavgrTx$fwdtransforms )
        zzaind[[k]]=smoothImage( asymmetry( zz[[k]], temp, doAsym  ), 0.5 )
        zzavg[[k]]=smoothImage(zz[[k]]*0.5+temp*0.5,0.5)
        zzmi[[k]] = antsImageMutualInformation( zzavgImg, zz[[k]] )
    }
    zzmi=unlist(zzmi)
}
```


```{r imat}
library(subtyper)
mask = antsImageRead("~/Downloads/PPMI_NM_template_crop_mask.nii.gz")
maskrr = maskImage( mask, mask, level = c( 2 ), binarize=TRUE )
maskb = maskImage( mask, mask, level = c( 1 ), binarize=TRUE ) %>% iMath("MD",2)
mysig=0.0
imato = imageListToMatrix( zzavg, maskb, sigma=mysig )
imatAsym = imageListToMatrix( zzaind, maskb, sigma=mysig )
imat = list( imato, imatAsym )
for ( k in 1:length( imat ) ) {
    iszero = imat[[k]] == 0
    imat[[k]][ iszero ]= NA
}
imatrr = imageListToMatrix( zzavg, maskrr )
imata=rowMeans(imato,na.rm=T)
imatrra=rowMeans(imatrr,na.rm=T)
library(lmerTest)
myeq = as.formula( 'nmsnc ~ (1|commonID)+(1|SITE)+nmrr + commonSex + age_BL + yearsbl + joinedDX' )
ppmiMatchedScl = scale_variables_in_equation( ppmiMatched, myeq, variables_to_exclude=c('yearsbl', 'nmrr', 'nmscl'))
ppmiMatchedScl=cbind(ppmiMatchedScl, nmmi = zzmi, nmsnc=imata, nmrr=imatrra )
lsel=ppmiMatchedScl$nmsnc < quantile(ppmiMatchedScl$nmsnc,0.995, na.rm=T) & ppmiMatchedScl$nmmi < quantile( ppmiMatchedScl$nmmi, 0.995,na.rm=T)
ppmiMatchedScl=ppmiMatchedScl[lsel,]
mdl = lmer( myeq, data=ppmiMatchedScl)
summary( mdl )
mycoef = coefficients( summary( mdl ) )
```




```{r imat2,fig.width=14,fig.height=6}
library(ggplot2)
library(visreg)
ppmiMatchedScl = scale_variables_in_equation( ppmiMatched, myeq, variables_to_exclude=c('yearsbl', 'nmrr', 'nmscl'))
ppmiMatchedScl=cbind(ppmiMatchedScl, nmrr=imatrra, nmsnc=imata, nmavgsnc=imat[[1]], nmasmsnc=imat[[2]] )
dxvar='joinedDX'
dxvar='DXSubAsyn'
mytbl = table(  ppmiMatchedScl[,dxvar ])
dxsel = names(mytbl[mytbl>=9])
if ( 'CNNegative' %in% names(mytbl) ) {
    ppmiMatchedScl[,dxvar ]=forcats::fct_relevel( ppmiMatchedScl[,dxvar ], 'CNNegative' )
} else ppmiMatchedScl[,dxvar ]=forcats::fct_relevel( ppmiMatchedScl[,dxvar ], 'CN' )
# lsel=ppmiMatchedScl$nmsnc<700 & !( ppmiMatchedScl$joinedDX %in% c("ProdromalSNCA","PDSNCA","PDPRKN"))
lsel=ppmiMatchedScl$nmsnc<700 & ( ppmiMatchedScl[,dxvar] %in% dxsel)
myeq = as.formula(paste( 'nmsnc ~ (1|commonID)+(1|SITE)+nmrr + commonSex + age_BL + yearsbl + ', dxvar ))
ppmiMatchedScl=ppmiMatchedScl[lsel,]
mdl = lmer( myeq, data=ppmiMatchedScl)
mycoef = coefficients( summary( mdl ) )
gg=grep(dxvar,rownames(mycoef))

sncnames = getNamesFromDataframe( "nmavgsnc", ppmiMatchedScl )
coefmat=matrix( NA, nrow=length(gg),ncol=sum(maskb==1))
coefmatpv=matrix( NA, nrow=length(gg),ncol=sum(maskb==1))
rownames(coefmat)=rownames(coefmatpv)=rownames(mycoef)[gg]
coefmatA=matrix( NA, nrow=length(gg),ncol=sum(maskb==1))
coefmatpvA=matrix( NA, nrow=length(gg),ncol=sum(maskb==1))
rownames(coefmatA)=rownames(coefmatpvA)=rownames(mycoef)[gg]
#########################
dookoo
output = run_voxel_analysis( sncnames, coefmat, coefmatpv, coefmatA, coefmatpvA, ppmiMatchedScl, dxvar,
    covariates = '~ (1 | commonID) + (1 | SITE) + nmrr + NM2DMT_NM_substantianigra_z_coordinate + commonSex + age_BL + yearsbl + ',
    show_plots = TRUE, threshold = 1e-4)
###############
for ( k in 1:nrow(output$coefmat) ) {
    outfn = paste0('/tmp/tvalue_',rownames(output$coefmat)[k],'.nii.gz')
    nsig=sum( p.adjust( na.omit(output$coefmatpv[k,]), 'BH' ) <= 0.05 )
    nsig2=sum( p.adjust( na.omit(output$coefmatpvA[k,]), 'BH' ) <= 0.05 )
    print( paste(outfn, nsig, nsig2 ) )
    timg = makeImage( maskb, antsrimpute( output$coefmat[k,] * (1.0) ) )
    timgA = makeImage( maskb, antsrimpute(output$coefmatA[k,] ))
    timgA1=antsApplyTransforms( zzavgImg, timgA, zzavgrTx$invtransforms )
    timg=timg+timgA1
    antsImageWrite( timg, outfn )
    }
###############
```

